---
- name: POST in Capacity DATA
  block: 
  - name: Insert Message into Capacity DATA
    uri:
      url: "{{ apex_url }}/{{ apex_uri }}/capacity_tracking/add_record"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: POST
      body_format: json
      body:  "{{ json_capacity }}"
      headers:
        Content-Type: "application/json"
        Cache-Control: "no-cache"
    register: capacity_json_response
  rescue:
  - name: Store the Json If APEX Server Is Down
    delegate_to: localhost
    lineinfile:
      path: "{{ json_backup_dir }}/capacity_json_response.json"
      line: "{{ capacity_json_response  | to_json }}"
      create: yes
    when: capacity_json_response.status == "500" or  capacity_json_response.status == -1
