---

- name: Upgrade Oracle Database
  hosts: '{{ host }}'
  become: yes
  roles:
    # - oraswgi-upgrade
    - oraswdb-upgrade
  
  ## Required Vars
  # oracle_db_home - This is where the upgrade will be move to (e.g. db_1) 
  # oracle_db_name - The db to be upgraded

  ## Optional vars
  # oracle_version (default: 12.1.0.2) 