---
- name: Copy duplicate_database.sql and duplicate Database
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  block:
  - name: Copy the duplicate_database.sql file
    template: 
      src: duplicate_database.j2
      dest: "{{ oracle_tmp }}/duplicate_database.sql"
  - name: startup nomount.
    command: "sqlplus / as sysdba @{{ oracle_tmp }}/startup_nomount.sql"
    register: opt2
    failed_when: '"ERROR" in opt2.stdout'
  - name: duplicate Database
    command: "rman target sys/{{ sourec_db_password }}@{{ source_db }} auxiliary sys/{{ target_db_password }}@{{ target_db }} @{{ oracle_tmp }}/duplicate_database.sql"
  when: inventory_hostname != master_node
  
- name: Entry for the new database
  lineinfile:
    path: /etc/oratab
    line: '{{ oracle_db_name }}:{{ oracle_home }}:N		# line added by Agent'
  become: yes
  when: inventory_hostname != master_node
  
