---

- name: Get {{ curr_db_name }} Database Home
  environment: "{{ ora_user_env }}"
  command: srvctl config database -d {{ curr_db_name }}
  changed_when: False
  register: db_config

- set_fact:
    oracle_db_name: "{{ curr_db_name | replace(' ','') }}"
    oracle_home_db: "{{ db_config.stdout | regex_search('home: .*') | regex_replace('home: (.*)','\\1' )}}"

- name: Check {{ curr_db_name }} Database Status
  environment: "{{ ora_user_env }}"
  command: srvctl status database -d {{ curr_db_name }}
  changed_when: False
  register: db_status

# - name: Start {{ oracle_db_name }} Database
#   environment: "{{ ora_user_env }}"
#   command: srvctl start database -db {{ oracle_db_name }}
#   when: "'Database is running.' not in db_status.stdout"

- include_role:
    name: oracle_admin
    tasks_from: start_db.yml
  vars:
    oracle_home: "{{ oracle_grid_home }}"
  when: "'Database is running.' not in db_status.stdout"
  # when: 
  # - patch_type == 'RDBMS'
  # - db_name_list | length > 0
  # - inventory_hostname == master_node

- name: Wait for DB to start
  pause:
    seconds: 60

- name: get oracle_sid
  shell: ps -ef | grep ora_smon | grep {{ oracle_db_name }} | grep -v grep | awk '{ print $8 }'
  register: ps_grep_smon
  changed_when: False

- name: set oracle_sid
  set_fact:
    oracle_db_sid: "{{ ps_grep_smon.stdout | regex_replace('.*_smon_(.*)', '\\1') }}"

- debug:
    var: ora_user_env

- block: 
  # https://github.com/ansible/ansible/issues/22025
  # role variables can not be overwritten
  - name: Run datapatch on {{ oracle_db_name }}
    become: yes
    become_user: "{{ oracle_user }}"
    environment:
      ORACLE_BASE: "{{ oracle_base }}"
      ORACLE_SID: "{{ oracle_db_sid }}"
      ORACLE_UNQNAME: "{{ oracle_db_name }}"
      ORACLE_HOME: "{{ oracle_home_db }}"
      NLS_LANG: "American_America.UTF8"
      PATH: "{{ oracle_home }}/bin:{{ oracle_tmp }}/{{ ojvm_patch }}:{{ oracle_home_db }}/OPatch:{{ ansible_env.PATH }}"
      TMP: "/u01/app/oracle"
      TMPDIR: "/u01/app/oracle"
    command: datapatch -verbose
    ignore_errors: yes
    register: datapatch

  - name: save datapatch stdout
    copy:
      dest: "{{ oracle_tmp }}/{{ oracle_db_name }}_datapatch.out"
      content: "{{ datapatch.stdout }}"
    changed_when: False

  - name: save datapatch stderr
    copy:
      dest: "{{ oracle_tmp }}/{{ oracle_db_name }}_datapatch.err"
      content: "{{ datapatch.stderr }}"
    changed_when: False
    when: datapatch.stderr_lines | length > 0

  - name: add failures to datapatch_failures
    set_fact:
      datapatch_failures: "{{ datapatch_failures }} + ['{{ oracle_db_name }}']"
    when: datapatch is failed
  when: oracle_sid != ''
