---
oragrid_group:
- oinstall

oracle_user:
- oradb
- oragrid

oracle_groups:
- oinstall
- dbadmin
- dboper

installation_type: "{% if ansible_play_hosts | length > 1 -%}rac
                    {%- else -%}standalone
                    {%- endif %}"

pbis:
    ignored_users:
        - root
        - oracle
    ignored_groups:
        - tty
        - root
        - oinstall
        - dba

asm_disk_location: /dev/oracleasm/disks

# DATA and RECO disks will be varied depending on the operational incremental expansions
asm_data_pattern: D*

asm_reco_pattern: R*

asm_exp_pattern: EXP*

asm_gg_pattern: GG*

asm_ocr_pattern: GRID_DISK*

kernel_parameters:
    kernel_sem: "250 46000 100 200"
    fs_aio_max_nr: "1048576"
    net_ipv4_ip_local_port_range: "9000 65500"
    net_core_rmem_default: "262144"
    net_core_rmem_max: "4194304"
    net_core_wmem_default: "262144"
    net_core_wmem_max: "1048576"
    fs_file_max: "6815744"
    kernel_shmmax: "4294967295"
    kernel_shmall: "2097152"
    kernel_shmmni: "4096"

    

required_rpms:
  - bc
  - binutils
  - compat-libcap1
  - compat-libstdc++-33
  - elfutils-libelf
  - elfutils-libelf-devel
  - fontconfig-devel
  - glibc
  - glibc-devel
  - ksh
  - libaio
  - libaio-devel
  - libX11
  - libXau
  - libXi
  - libXtst
  - libXrender
  - libXrender-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libxcb
  - make
  - smartmontools
  - sysstat

