---
- include_role:
    name: oracle_ACFS
    tasks_from: configure_acfs.yml
  vars:
    diskgroup: "{{ exp_dg }}"
  when:
  - create_exp_diskgroup
  - oracle_base + '/' + exp_dg.dir not in ansible_mounts | json_query('[].mount')

- include_role:
    name: oracle_ACFS
    tasks_from: configure_acfs.yml
  vars:
    diskgroup: "{{ gg_dg }}"
  when:
  - create_gg_diskgroup
  - oracle_base + '/' + gg_dg.dir not in ansible_mounts | json_query('[].mount')