---

- name: check if post_provisioning_done check file exists
  stat:
    path: "{{ oracle_base }}/admin/.post_provisioning_done_{{ oracle_db_name }}"
  register: post_provisioning_done

- include_tasks: post_provision_db.yml
  when: post_provisioning_done.stat.exists == false

- include_tasks: alter_db_params.yml
  when: alter_params == true
