# cxoracle-install playbook
---
- name: Install cx_oracle
  pip:
     name=cx_Oracle==7.3
     extra_args="{{ extra_args }}"
     umask={{ cx_oracle_umask | default (omit)}}
     state=present
  #with_items: "{{oracle_databases}}"
  when: install_cx_oracle
  tags: cx_oracle
  #environment: "{{oracle_env}}"
